### ISSUE TITLE
Could you please unpublish the parse-url package?

### ISSUE THREAD

**Issue by IonicaBizau** [talon/you-must-be-so-good-at-math#1]
Hi there!

I developed an _advanced_ url parsing library (which can parse git urls and more) and I'd really like if you unpublished the `parse-url` package.

`npm unpublish parse-url`-ing will not affect the dependents (since others cannot publish the same version on npm again). I would like to publish my package there.

Could you do that?

Thanks! :cake:

**Comment by talon** [comment]
Yeah, I've had it deprecated for awhile now. I'll unpublish now.

**Comment by IonicaBizau** [comment]
@LegitTalon Thanks, but it seems it not unpublished yet. Can you please double check the `npm unpublish parse-url` output? On the other side, maybe npm has some special caching or so... :smile:

**Comment by talon** [comment]
@IonicaBizau It is unpublished

**Comment by IonicaBizau** [comment]
@LegitTalon Thanks! :dizzy: Probably it was just a timing issue. :apple:
